name: Teste de Agendamento

on:
  schedule:
    - cron: '*/5 * * * *'  # a cada 5 minutos
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Agendamento funcionando"
