name: Atualizar Alertas MapBiomas

on:
  schedule:
    - cron: '0 3 * * 1'  # roda toda segunda-feira às 3h UTC
  workflow_dispatch:

jobs:
  atualizar_alertas:
    runs-on: ubuntu-latest

    env:
      GDRIVE_TOKEN: ${{ secrets.GDRIVE_TOKEN }}

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar pacotes R
        run: |
          Rscript -e 'install.packages(c("sf", "dplyr", "googledrive", "gargle"))'

      - name: Rodar script de atualização
        run: Rscript update_alertas.R