name: Atualizar Alertas MapBiomas

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  atualizar_alertas:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.local/share/renv/library
          key: Linux-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            Linux-r-

      - name: Instalar dependências (via pak)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            sf
            dplyr
            googledrive
            gargle

      - name: Autenticar Google Drive
        run: |
          printf '%s' "$GDRIVE_TOKEN" > credencial.json
        env:
          GDRIVE_TOKEN: ${{ secrets.GDRIVE_TOKEN }}

      - name: Rodar script R
        run: Rscript update_alertas.R
