name: Teste sem GDRIVE_TOKEN

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  testar_schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Echo simples
        run: echo "Rodando sem secrets"
