name: Atualizar Alertas MapBiomas

on:
  schedule:
    - cron: '0 3 * * 1'  # Segunda às 3h UTC = meia-noite em Brasília
  workflow_dispatch:

jobs:
  atualizar_alertas:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar pacotes R
        run: |
          Rscript -e 'install.packages(c("sf", "dplyr", "googledrive", "gargle"))'

      - name: Criar arquivo de credenciais
        run: echo "${{ secrets.GDRIVE_TOKEN }}" > credencial.json

      - name: Rodar script de atualização
        run: Rscript update_alertas.R