name: Atualizar Alertas MapBiomas

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  atualizar_alertas:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar dependências de sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev

      - name: Instalar pacotes R
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: sf, dplyr, googledrive, gargle

      - name: Criar arquivo de credenciais
        run: |
          echo '${{ secrets.GDRIVE_TOKEN }}' > credencial.json

      - name: Rodar script de atualização
        run: Rscript update_alertas.R