name: Atualizar Alertas MapBiomas

on:
  schedule:
    - cron: '0 3 * * 1'  # segunda-feira às 3h UTC = meia-noite em Brasília
  workflow_dispatch:

jobs:
  atualizar_alertas:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar pacotes R com dependências do sistema
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            sf
            dplyr
            googledrive
            gargle

      - name: Autenticar Google Drive
        run: echo "GDRIVE_TOKEN=${{ secrets.GDRIVE_TOKEN }}" >> $GITHUB_ENV

      - name: Rodar script de atualização
        run: Rscript update_alertas.R