name: Atualizar Alertas MapBiomas

on:
  schedule:
    - cron: '0 3 * * 1'  # toda segunda-feira às 3h UTC
  workflow_dispatch:

jobs:
  atualizar_alertas:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar dependências
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            sf
            dplyr
            googledrive
            gargle

      - name: Autenticar Google Drive
        run: |
          echo '${{ secrets.GDRIVE_TOKEN }}' > credencial.json

      - name: Rodar script R
        run: Rscript update_alertas.R