name: Atualizar Alertas MapBiomas

on:
  schedule:
    - cron: '0 3 * * 1'  # segunda-feira às 3h UTC = meia-noite em Brasília

jobs:
  atualizar_alertas:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Definir variável GDRIVE_TOKEN
        run: echo "GDRIVE_TOKEN=${{ secrets.GDRIVE_TOKEN }}" >> $GITHUB_ENV

      - name: Instalar pacotes R
        run: |
          Rscript -e 'install.packages(c("sf", "dplyr", "googledrive", "gargle"))'

      - name: Rodar script de atualização
        run: Rscript update_alertas.R